### ISSUE TITLE
Deprecation error causing build error [ BidirectionalIterator]

### ISSUE THREAD

**Issue by dawit-michael** [jpnurmi/interval_tree#2]
![image](https://github.com/jpnurmi/interval_tree/assets/32758991/da139c10-92cc-4949-a7a7-7ae6154a679d)
This issue is resulting in an error mentioned in [item_selector ](https://github.com/jpnurmi/item_selector) package issues [link](https://github.com/jpnurmi/item_selector/issues/3#issue-1698954554)

**Comment by slightfoot** [comment]
@dawit-michael This is now resolved as of interval_tree: 0.4.1
